export let elementCollection = {
  hiddenBrands: [],
  hiddenDeviceType: [],
  hiddenBrandsFlag: true,
  hiddenDeviceTypeFlag: true,
  menuOpenFlag: false,
  main: document.querySelector('body'),
  description: document.querySelector('.company-info__description'),
  readMoreDescriptionButton: document.querySelector('#read-more-description'),
  showAllBrandsButton: document.querySelector('#show-all-brands'),
  showAllDeviceTypeButton: document.querySelector('#show-all-device-type'),
  showMenuButton: document.querySelector('.icon--menu'),
  overlayMenu: document.querySelector('.overlay--menu'),
  feedBackOverlay: document.querySelector('#feed-back-overlay'),
  callBackOverlay: document.querySelector('#call-back-overlay'),
  closeButton: document.querySelector('#side-menu-close-button'),
  feedBackCloseButton: document.querySelector('#feed-back-close-button'),
  callBackCloseButton: document.querySelector('#call-back-close-button'),
  feedBackModal: document.querySelector('#feed-back-modal'),
  callBackModal: document.querySelector('#call-back-modal'),
  sideMenu: document.querySelector('.menu--side'),
}
